"""Write a local-development `.env` from the running Supabase stack.

Usage: uv run python scripts/dev_env.py [--force]
Requires the local stack (`npx supabase@2.119.0 start --workdir infra ...`). Generates random passwords for
the runtime DB roles. Refuses to overwrite an existing `.env` unless --force.
"""

import json
import secrets
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV = ROOT / ".env"


def _quote(value: str) -> str:
    return f'"{value}"' if any(c in value for c in " #'$") else value


def main() -> None:
    if ENV.exists() and "--force" not in sys.argv:
        sys.exit(".env already exists; re-run with --force to regenerate (role passwords will change).")
    out = subprocess.run(
        "npx --yes supabase@2.119.0 status -o json --workdir infra",
        cwd=ROOT, shell=True, capture_output=True, text=True, check=True,
    ).stdout
    status = json.loads(out[out.index("{"):])
    api_pw, worker_pw = secrets.token_urlsafe(24), secrets.token_urlsafe(24)
    db_host = "127.0.0.1:54322"
    values = {
        "PAWGUARD_ENV": "development",
        "PAWGUARD_DEMO_MODE": "true",
        "PAWGUARD_LOG_LEVEL": "INFO",
        "PAWGUARD_DB_API_PASSWORD": api_pw,
        "PAWGUARD_DB_WORKER_PASSWORD": worker_pw,
        "PAWGUARD_DATABASE_URL": f"postgresql://pawguard_api:{api_pw}@{db_host}/postgres",
        "PAWGUARD_WORKER_DATABASE_URL": f"postgresql://pawguard_worker:{worker_pw}@{db_host}/postgres",
        "PAWGUARD_MIGRATE_DATABASE_URL": status["DB_URL"],
        "PAWGUARD_TEST_DATABASE_NAME": "pawguard_test",
        "PAWGUARD_SUPABASE_URL": status["API_URL"],
        "PAWGUARD_SUPABASE_PUBLIC_URL": status["API_URL"],
        "PAWGUARD_SUPABASE_SECRET_KEY": status["SECRET_KEY"],
        "PAWGUARD_STORAGE_BUCKET": "pawguard-media",
        "PAWGUARD_AUTH_AUDIENCE": "authenticated",
        "PAWGUARD_REDIS_URL": "redis://127.0.0.1:6379/0",
        "PAWGUARD_API_INTERNAL_URL": "http://127.0.0.1:8000",
        "PAWGUARD_WEB_ORIGIN": "http://localhost:3000",
        "PAWGUARD_DEFAULT_TIMEZONE": "Asia/Kolkata",
        "PAWGUARD_SUPABASE_PUBLISHABLE_KEY": status["PUBLISHABLE_KEY"],
        "PAWGUARD_MAP_TILE_URL": "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
        "PAWGUARD_MAP_TILE_ATTRIBUTION": "© OpenStreetMap contributors",
    }
    ENV.write_text("# Generated by scripts/dev_env.py for LOCAL DEVELOPMENT ONLY.\n"
                   + "".join(f"{k}={_quote(v)}\n" for k, v in values.items()), encoding="utf-8")
    print(f"Wrote {ENV}")


if __name__ == "__main__":
    main()
