"""Generate docs/PERMISSIONS.md: role templates × capabilities, and every endpoint's documented permission.

Usage: uv run python scripts/gen_permissions.py
"""

import os
import re
from pathlib import Path

os.environ.setdefault("PAWGUARD_DATABASE_URL", "postgresql://x:x@localhost/x")
os.environ.setdefault("PAWGUARD_SUPABASE_URL", "http://localhost:54321")
os.environ["PAWGUARD_ENV_FILE"] = os.devnull

from pawguard_api.capabilities import PROFESSIONAL_SCOPE_FOR, ROLE_TEMPLATES, Cap, Role
from pawguard_api.main import create_app

ROOT = Path(__file__).resolve().parent.parent


def main() -> None:
    roles = list(Role)
    lines = ["# Permission matrix", "",
             "Generated by `scripts/gen_permissions.py`. Authorisation = active membership in the selected organisation"
             " + capability on that membership (+ an approved professional authority where marked) + record scope. Role"
             " names only choose the *initial* capability template; administrators can adjust capabilities per member.",
             "", "## Role templates", "",
             "| Capability | " + " | ".join(r.value for r in roles) + " |",
             "|---|" + "---|" * len(roles)]
    for cap in Cap:
        extra = f" (+ `{PROFESSIONAL_SCOPE_FOR[cap]}` approval)" if cap in PROFESSIONAL_SCOPE_FOR else ""
        lines.append(f"| `{cap.value}`{extra} | " + " | ".join("✓" if cap in ROLE_TEMPLATES[r] else "" for r in roles) + " |")
    lines += ["", "Notes: `org_admin` deliberately lacks `vaccination.review`; nobody can approve their own professional "
              "authority (API check + database constraint). Residents and content reviewers get capabilities in later "
              "phases.", "", "## Endpoints", "", "| Method | Path | Permission (from the endpoint documentation) |",
              "|---|---|---|"]
    spec = create_app().openapi()
    for path, ops in sorted(spec["paths"].items()):
        for method, op in ops.items():
            desc = (op.get("description") or "").split("\n\n")[0]
            m = re.search(r"Permission:\s*(.+?)(?:\.\s|\.$|$)", desc.replace("\n", " "))
            perm = m.group(1).strip() if m else ("public" if path.startswith("/health") else "—")
            lines.append(f"| {method.upper()} | `{path}` | {perm} |")
    out = ROOT / "docs" / "PERMISSIONS.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
