"""Test vectors for the browser certificate verifier, produced by the SERVER's signing code (cross-language check).

Uses throwaway TEST keys derived from fixed bytes — never used anywhere else. Writes
apps/web/src/lib/verify/__fixtures__/vectors.json. Run: uv run python scripts/make_verify_vectors.py
"""

import base64
import hashlib
import json
import uuid
from pathlib import Path

import cbor2
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from pawguard_api.integrations import cose

OUT = Path(__file__).resolve().parents[1] / "apps/web/src/lib/verify/__fixtures__/vectors.json"


def test_key(label: str) -> Ed25519PrivateKey:
    return Ed25519PrivateKey.from_private_bytes(hashlib.sha256(f"pawguard-TEST-ONLY-{label}".encode()).digest())


def pub(k: Ed25519PrivateKey) -> bytes:
    return k.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)


ROOT, OTHER_ROOT = test_key("root"), test_key("other-root")
ACTIVE, RETIRED, REVOKED, UNKNOWN = (test_key(n) for n in ("active", "retired", "revoked", "unknown"))
KID = {"active": bytes.fromhex("a1a1a1a1a1a1a1a1"), "retired": bytes.fromhex("b2b2b2b2b2b2b2b2"),
       "revoked": bytes.fromhex("c3c3c3c3c3c3c3c3"), "unknown": bytes.fromhex("d4d4d4d4d4d4d4d4")}
CLINIC = uuid.UUID("11111111-2222-3333-4444-555555555555")
T0, T_RETIRE, T_NOW = 1_700_000_000, 1_750_000_000, 1_790_000_000


def payload(cid: uuid.UUID, iat: int, given: str = "2026-06-09", due: str | None = "2027-06-09") -> dict:
    vac = {1: "Rabies vaccine (demo product)", 3: given, 5: "vet"}
    if due:
        vac[4] = due
    return {1: 1, 2: cid.bytes, 3: {1: "PG-TEST-0001", 2: "Bruno", 3: "dog", 4: "male", 5: "Brown, white chest"},
            4: vac, 5: {1: CLINIC.bytes, 2: "Demo — Test Clinic"}, 6: "Dr Test", 7: iat}


def cert(key: Ed25519PrivateKey, kid: bytes, cid: uuid.UUID, iat: int, **kw: str | None) -> str:
    return cose.to_qr_text(cose.sign1(payload(cid, iat, **kw), kid, key))


def signed_list(fmt: str, body: dict, root: Ed25519PrivateKey = ROOT) -> dict:
    return {"format": fmt, "version": body[1],
            "cose": base64.b64encode(cose.sign1(body, cose.ROOT_KID, root)).decode()}


def main() -> None:
    entry = lambda kid, key, status, frm, to=None: {k: v for k, v in {  # noqa: E731
        1: KID[kid], 2: CLINIC.bytes, 3: "Demo — Test Clinic", 4: pub(key), 5: frm, 6: to, 7: status, 8: True}.items()
        if v is not None}
    trust_body = {1: 7, 2: T_NOW, 3: [entry("active", ACTIVE, "active", T_RETIRE),
                                      entry("retired", RETIRED, "retired", T0, T_RETIRE),
                                      entry("revoked", REVOKED, "revoked", T0, T_RETIRE)], 4: 7}
    revoked_id = uuid.UUID("99999999-0000-4000-8000-000000000001")
    rl_body = {1: 3, 2: T_NOW, 3: [revoked_id.bytes]}
    trust = signed_list("PG-TL1", trust_body)
    tampered_body = dict(trust_body)
    tampered_body[3] = [*trust_body[3], entry("unknown", UNKNOWN, "active", T0)]  # attacker adds their own key
    msg = cose.parse_sign1(base64.b64decode(trust["cose"]))
    forged_trust = {"format": "PG-TL1", "version": 7, "cose": base64.b64encode(cbor2.dumps(cbor2.CBORTag(
        18, [msg.protected, {}, cbor2.dumps(tampered_body), msg.signature]))).decode()}

    genuine = cert(ACTIVE, KID["active"], uuid.uuid4(), T_NOW)
    g = cose.parse_sign1(cose.from_qr_text(genuine))
    altered_payload = dict(g.payload)
    altered_payload[4] = {**g.payload[4], 3: "2026-06-10"}
    altered = cose.to_qr_text(cbor2.dumps(cbor2.CBORTag(18, [g.protected, {}, cbor2.dumps(altered_payload),
                                                             g.signature])))
    raw = cose.from_qr_text(genuine)
    byte_flips = []
    body_at = raw.find(g.body)
    for i in range(0, len(g.body), max(1, len(g.body) // 40)):  # 40 positions across the signed payload
        b = bytearray(raw)
        b[body_at + i] ^= 0x01
        byte_flips.append(cose.to_qr_text(bytes(b)))
    vectors = {
        "note": "TEST-ONLY keys derived from fixed strings; generated by scripts/make_verify_vectors.py",
        "root_public_b64": base64.b64encode(pub(ROOT)).decode(),
        "today": "2026-10-07",
        "trust": trust, "trust_forged": forged_trust,
        "trust_other_root": signed_list("PG-TL1", trust_body, OTHER_ROOT),
        "revocations": signed_list("PG-RL1", rl_body),
        "certs": {
            "genuine": genuine,
            "altered": altered,
            "unknown_key": cert(UNKNOWN, KID["unknown"], uuid.uuid4(), T_NOW),
            "revoked_credential": cert(ACTIVE, KID["active"], revoked_id, T_NOW),
            "revoked_key": cert(REVOKED, KID["revoked"], uuid.uuid4(), T0 + 100),
            "retired_before": cert(RETIRED, KID["retired"], uuid.uuid4(), T0 + 100),
            "retired_after": cert(RETIRED, KID["retired"], uuid.uuid4(), T_RETIRE + 10_000),
            "overdue": cert(ACTIVE, KID["active"], uuid.uuid4(), T_NOW, given="2025-01-01", due="2026-01-01"),
            "kid_swapped": cose.to_qr_text(cose.sign1(payload(uuid.uuid4(), T_NOW), KID["active"], UNKNOWN)),
        },
        "byte_flips": byte_flips,
        "unreadable": ["", "hello", "https://example.org/card/abc", "PG1:", "PG1:%%%%", "PG1:" + "A" * 2100,
                       "HC1:6BFOXN*TS0BI$ZD4N9", "PG1:" + "0" * 30],
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(vectors, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(genuine)}-character genuine certificate)")


if __name__ == "__main__":
    main()
