import type { Schemas } from "@pawguard/api-client";
import { BadgeCheck, Info } from "lucide-react";
import { getTranslations } from "next-intl/server";

import { formatPartialDate } from "@/lib/format";

type Data = Schemas["PetCertificatesOut"];

function Qr({ svg, label }: { svg: string; label: string }) {
  return (
    <div
      className="w-56 max-w-full shrink-0 rounded-control border border-divider bg-white p-2 [&_svg]:h-auto [&_svg]:w-full"
      role="img"
      aria-label={label}
      // SVG generated by our API from the signed certificate (no user-supplied markup).
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}

/** Tamper-proof certificates: the latest verified rabies vaccination first, the others behind "Show verify QR". */
export async function SignedCertificates({ data, locale }: { data: Data; locale: string }) {
  const t = await getTranslations("pets.signed");
  const tc = await getTranslations("common");
  const fmt = (d: string | null | undefined) => formatPartialDate(d, "day", locale, tc("notRecorded"));
  const featured = data.items.find((i) => i.event_id === data.featured_event_id && i.qr_svg);
  const others = data.items.filter((i) => i !== featured);
  const line = (i: Data["items"][number]) =>
    `${t("given", { date: fmt(i.administered_on) })}${i.next_due_on ? ` · ${t("nextDue", { date: fmt(i.next_due_on) })}` : ""}`;

  return (
    <section aria-labelledby="signed-h" className="mx-auto w-full max-w-xl space-y-4 rounded-card border border-divider bg-surface p-5" data-testid="signed-certificates">
      <h2 id="signed-h" className="flex items-center gap-2 text-lg">
        <BadgeCheck aria-hidden className="size-5 text-primary" />
        {t("title")}
      </h2>
      {featured?.qr_svg ? (
        <figure className="flex flex-col items-center gap-2 sm:flex-row sm:items-start">
          <Qr svg={featured.qr_svg} label={t("qrLabel", { vaccine: featured.vaccine ?? "" })} />
          <figcaption className="space-y-1">
            <p className="font-display font-semibold">{t("scanToVerify")}</p>
            <p className="text-sm">{featured.vaccine}</p>
            <p className="text-sm text-ink-2">{line(featured)}</p>
          </figcaption>
        </figure>
      ) : (
        <p className="text-sm text-ink-2">{t("noRabies")}</p>
      )}
      {others.length ? (
        <ul className="divide-y divide-divider text-sm">
          {others.map((i) => (
            <li key={i.event_id} className="py-2">
              <p className="font-semibold">{i.vaccine}</p>
              <p className="text-ink-2">{line(i)}</p>
              {i.qr_svg ? (
                <details className="mt-1">
                  <summary className="min-h-11 cursor-pointer content-center font-semibold">{t("showQr")}</summary>
                  <div className="mt-2 flex flex-col items-start gap-1">
                    <Qr svg={i.qr_svg} label={t("qrLabel", { vaccine: i.vaccine ?? "" })} />
                    <p className="text-xs text-ink-2">{t("scanToVerify")}</p>
                  </div>
                </details>
              ) : (
                <p className="text-ink-2">{t("notIssued")}</p>
              )}
            </li>
          ))}
        </ul>
      ) : null}
      <p className="flex gap-2 text-sm">
        <Info aria-hidden className="mt-0.5 size-4 shrink-0" />
        <span>
          {t("ownerEntered")}
          {data.unverified_count ? ` ${t("waiting", { count: data.unverified_count })}` : ""}
        </span>
      </p>
      <p className="text-xs text-ink-2">{t("honesty")}</p>
    </section>
  );
}
