import { Download, ExternalLink } from "lucide-react";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";

import { Button, Card, Notice } from "@pawguard/ui";

import { PageBody, PageHeader } from "@/components/page-header";
import { CardActions } from "@/components/pets/card-actions";
import { pageContext } from "@/lib/page-context";
import { requestOrigin } from "@/lib/web-origin";

/** The owner's view of the pet's vaccination card: QR code, public link, PDF, regenerate or turn off. */
export default async function PetCardPage({ params }: { params: Promise<{ locale: string; id: string }> }) {
  const { locale, id } = await params;
  setRequestLocale(locale);
  const ctx = await pageContext();
  const t = await getTranslations("pets.card");
  const origin = await requestOrigin();
  const { data, response } = await ctx.api.GET("/api/v1/my/pets/{pet_id}/card", {
    params: { path: { pet_id: id }, query: { base_url: origin } },
  });
  if (response.status === 404 || response.status === 422) notFound();
  if (!data) return <PageBody><Notice tone="urgent">{t("failed")}</Notice></PageBody>;
  const publicUrl = `${origin}${data.url_path}`;
  const pdfHref = `/api/v1/my/pets/${id}/card.pdf?base_url=${encodeURIComponent(origin)}`;

  return (
    <PageBody>
      <PageHeader title={t("title")} intro={t("intro")} back={{ href: `/app/pets/${id}`, label: t("back") }} />
      <Card className="flex flex-wrap items-start gap-6">
        <div
          className="w-56 max-w-full shrink-0 rounded-control border border-divider bg-white p-2 [&_svg]:h-auto [&_svg]:w-full"
          role="img"
          aria-label={t("qrAlt")}
          // SVG generated by our API from the card URL (no user-supplied markup).
          dangerouslySetInnerHTML={{ __html: data.qr_svg }}
        />
        <div className="min-w-0 flex-1 space-y-3">
          <p className="text-sm text-ink-2">{t("scanHint")}</p>
          <p className="text-sm break-all">
            <a href={publicUrl} target="_blank" rel="noopener noreferrer">
              {publicUrl}
              <ExternalLink aria-hidden className="ml-1 inline size-4" />
            </a>
          </p>
          <div className="flex flex-wrap gap-2">
            <Button asChild>
              <a href={pdfHref} download>
                <Download aria-hidden className="size-5" />
                {t("downloadPdf")}
              </a>
            </Button>
          </div>
          <Notice tone="neutral">{t("disclaimer")}</Notice>
          <p className="text-sm text-ink-2">{t("shows")}</p>
          <CardActions petId={id} baseUrl={origin} />
        </div>
      </Card>
    </PageBody>
  );
}
