import { Download, ExternalLink, ShieldCheck } from "lucide-react";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";

import { Button, Notice } from "@pawguard/ui";

import { PageBody, PageHeader } from "@/components/page-header";
import { CardActions } from "@/components/pets/card-actions";
import { PetAvatar, PetStatusChip } from "@/components/pets/status";
import { formatPartialDate } from "@/lib/format";
import { pageContext } from "@/lib/page-context";
import { requestOrigin } from "@/lib/web-origin";

/** The owner's view of the pet's vaccination card, shown as a wallet card: QR, verified vaccines, PDF. */
export default async function PetCardPage({ params }: { params: Promise<{ locale: string; id: string }> }) {
  const { locale, id } = await params;
  setRequestLocale(locale);
  const ctx = await pageContext();
  const t = await getTranslations("pets.card");
  const tp = await getTranslations("pets");
  const tc = await getTranslations("common");
  const origin = await requestOrigin();
  const [{ data, response }, petRes] = await Promise.all([
    ctx.api.GET("/api/v1/my/pets/{pet_id}/card", { params: { path: { pet_id: id }, query: { base_url: origin } } }),
    ctx.api.GET("/api/v1/my/pets/{pet_id}", { params: { path: { pet_id: id } } }),
  ]);
  if (response.status === 404 || response.status === 422) notFound();
  const pet = petRes.data;
  if (!data || !pet) return <PageBody><Notice tone="urgent">{t("failed")}</Notice></PageBody>;
  const publicUrl = `${origin}${data.url_path}`;
  const pdfHref = `/api/v1/my/pets/${id}/card.pdf?base_url=${encodeURIComponent(origin)}`;
  const verified = pet.timeline.filter((e) => e.verification === "verified_by_vet");
  const fmt = (d: string | null | undefined) => formatPartialDate(d, "day", locale, tc("notRecorded"));

  return (
    <PageBody>
      <PageHeader title={t("title")} intro={t("intro")} back={{ href: `/app/pets/${id}`, label: t("back") }} />

      <article aria-label={t("walletLabel", { name: pet.name })} className="mx-auto w-full max-w-xl overflow-hidden rounded-2xl border border-divider bg-surface shadow-card">
        <div className="flex items-center justify-between gap-3 bg-primary px-5 py-3 text-white">
          <p className="flex items-center gap-2 font-display font-semibold">
            <ShieldCheck aria-hidden className="size-5" />
            {t("walletTitle")}
          </p>
          <p className="text-sm">PawGuard 360</p>
        </div>
        <div className="grid gap-5 p-5 sm:grid-cols-[1fr_auto]">
          <div className="min-w-0 space-y-3">
            <div className="flex items-center gap-3">
              <PetAvatar url={pet.photo_url} name={pet.name} />
              <div className="min-w-0">
                <p className="font-display text-xl font-semibold">{pet.name}</p>
                <p className="text-sm text-ink-2">
                  {tp(`species.${pet.species as "dog" | "cat"}`)} · {pet.clinic_name}
                </p>
              </div>
            </div>
            <PetStatusChip status={pet.status} />
            <div>
              <p className="text-sm font-semibold">{t("verifiedList")}</p>
              {verified.length === 0 ? (
                <p className="text-sm text-ink-2">{tp("status.no_verified_record")}</p>
              ) : (
                <ul className="mt-1 divide-y divide-divider text-sm">
                  {verified.map((e) => (
                    <li key={e.event_id} className="py-1.5">
                      <span className="font-semibold">{e.vaccine}</span>
                      <span className="block text-ink-2">
                        {tp("givenOn", { date: fmt(e.administered_on) })}
                        {e.next_due_on ? ` · ${tp("nextDue", { date: fmt(e.next_due_on) })}` : ""}
                      </span>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </div>
          <div
            className="mx-auto w-44 shrink-0 rounded-control border border-divider bg-white p-2 sm:mx-0 [&_svg]:h-auto [&_svg]:w-full"
            role="img"
            aria-label={t("qrAlt")}
            // SVG generated by our API from the card URL (no user-supplied markup).
            dangerouslySetInnerHTML={{ __html: data.qr_svg }}
          />
        </div>
        <p className="border-t border-divider px-5 py-3 text-xs text-ink-2">{t("disclaimer")}</p>
      </article>

      <div className="mx-auto w-full max-w-xl space-y-4">
        <Button asChild size="lg" block>
          <a href={pdfHref} download>
            <Download aria-hidden className="size-5" />
            {t("downloadPdf")}
          </a>
        </Button>
        <p className="text-sm text-ink-2">{t("scanHint")}</p>
        <p className="text-sm break-all">
          <a href={publicUrl} target="_blank" rel="noopener noreferrer">
            {publicUrl}
            <ExternalLink aria-hidden className="ml-1 inline size-4" />
          </a>
        </p>
        <CardActions petId={id} baseUrl={origin} />
      </div>
    </PageBody>
  );
}
